name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0'

    - name: Restore dependencies
      run: dotnet restore SimpleCalculator/SimpleCalculator.csproj

    - name: Build
      run: dotnet build SimpleCalculator/SimpleCalculator.csproj --configuration Release --no-restore

    - name: Test
      run: dotnet test SimpleCalculator/SimpleCalculator.csproj --no-build --verbosity normal
